### ISSUE TITLE
topology generator: Missing IPs for multiple BRs in a single AS

### ISSUE THREAD

**Issue by sustrik** [scionproto/scion#3318]
When there are multiple BRs in a single AS, the docker-compose dispatcher entry contains an IP address for just one of them:

```
  scion_disp_br_1-ff00_0_111:
    container_name: scion_disp_br_1-ff00_0_111
    environment:
      SU_EXEC_USERSPEC: $LOGNAME
    image: scion_dispatcher_go
    networks:
      scn_002:
        ipv4_address: 242.254.0.34
    volumes:
       ...
```
Caused by this code in topology generator (in `python/topology/docker.py`):

```
        # Create dispatcher for BR Ctrl Port
        for k in topo.get("BorderRouters", {}):
            if k.endswith('-1'):
                ctrl_net = self.elem_networks[k + "_ctrl"][0]
                ctrl_ip = str(ctrl_net['ipv4'])
                break
        entry['networks'][self.bridges[ctrl_net['net']]] = {'ipv4_address': ctrl_ip}
```

Consequently, no BRs except for instance 1 are getting any ctrl-plane packets.
