### ISSUE TITLE
scion-pki: change TRC validity configuration

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#4440]
Entering TRC validity as a pair of not_before [UnixTime] and validity duration string makes it really human unfriendly.
I suggest we change it to not_before and not_after and use RFC3339 (e.g. 1990-12-31T23:59:60Z) time format

So instead of
```toml
[validity]
not_before = 1619352000
validity   = "367d"
```
we would configure:
```toml
[validity]
not_before = "2021-04-25T12:00:00Z"
not_after = "2022-04-27T12:00:00Z"
```

This would make TRC configuration much more readable.

Note that the parsing should allow both forms for a smooth migration.
