### ISSUE TITLE
proposal: pluggable segment registration

### ISSUE THREAD

**Issue by lukedirtwalker** [scionproto/scion#4726]
Authors: @lukedirtwalker, @oncilla

tl;dr: We propose a plugin system that allows the user to configure their custom
segment registration logic.

## Overview

Path registration is currently not customizable. By default all beacons that are
terminated in an AS are registered at the originating core AS. This means all
segments are public by default. This is not always desirable. Previously a
[hidden paths system](https://docs.scion.org/en/latest/hidden-paths.html) was
added. This hidden paths system allows an AS to decide who can get access to
some non-public path segments. However the approach requires additional
infrastructure and has not found wide-spread adoption.

In this proposal, we propose a more generic solution that allows flexible
segment registration policies to be implemented. To allow for this, we add a
plugin system that allows the user to configure their custom segment
registration logic. Plugins need to be compiled into the binary.

## Motivation

The current implementation of the SCION control service does not allow for any
different registration logic than what is currently implemented in the
opensource repository. We believe that by introducing a plugin system, we can
allow for experimentation with different registration policies.

As part of this proposal we want to implement a public registration plugin
(doing what the current public registration does) and a new hidden segment registration
plugin (see "Proposal: Hidden segments without extra infrastructure").

Apart from that, at Anapaya we have a specific desire to implement a custom
registration plugin.

## Proposal

We propose a plugin system. For this we extend the beacon policy to support
custom plugins. A plugin needs to be compiled into the binary. The details are
described below.

### Plugin API

A plugin is a Go struct that implements the following interface:

```go
type SegmentRegistrationPlugin interface {
    // ID returns the unique identifier of the plugin.
    ID() string
    // New creates a new instance of the plugin with the provided configuration.
    New(ctx context.Context, config map[string]any) (SegmentRegistrar, error)
    // Validate validates the configuration of the plugin.
    Validate(config map[string]any) error
}

type SegmentRegistrar interface {
    // RegisterSegments registers the given segments according to the plugin's logic.
    RegisterSegments(ctx context.Context, segments []*seg.PathSegment) (RegistrationStats, error)
}

type RegistrationStats struct {
    // Status contains the registration status for each segment.
    // If the segment was successfully registered, the error is nil.
    Status map[*seg.PathSegment]error
}
```

We need to define a plugin registry as follows:

```go
var segmentRegistrationPlugins = map[string]SegmentRegistrationPlugin{}

func RegisterPlugin(p SegmentRegistrationPlugin) {
    id := p.ID()
    if _, ok := segmentRegistrationPlugins[id]; ok {
        panic(fmt.Sprintf("plugin %q already registered", id))
    }
    segmentRegistrationPlugins[id] = p
}
```

A plugin must be constructed in the main code of the control service and
registered in a plugin registry. The plugin registry is a map from plugin name
to the SegmentRegistrationPlugin interface.

The plugin is then used depending on the beacon policy, which is described below.

We will need to change the implementation of the [SegmentWriters
method](https://github.com/scionproto/scion/blob/e14ce703acf48d950622133c13ae6557f8b49345/control/tasks.go#L125)
to dispatch based on the beacon policy to the different plugins as described
below.

### Beacon policy changes

Extend the
[beacon.Policy](https://github.com/scionproto/scion/blob/dd086a53c7722082a6c4b5dbf9cef57d5a549066/control/beacon/policy.go#L177-L191)
to support attaching a plugin configuration to a subset of beacons.

We propose that beacons are matched based on the combination of a `pathpol.ACL`
and `pathpol.Sequence` (similar to a path policy in the gateway). The operator
can express a list of mappings from matchers to "plugin configurations". All
beacons that do not match are registered with the default public registration
plugin.

Specifically we propose to extend the `beacon.Policy` with a list of
`RegistrationPolicies`. Each `RegistrationPolicy` consists of the following fields:

- `Name`: A descriptive name for the policy.
- `Description`: A description of the policy.
- `Matcher`: Is used to match the beacon, it contains the following fields:
    - `Sequence`: An optional sequence of `pathpol.Sequence` that need to match.
    - `ACL`: An optional `pathpol.ACL` that needs to match.
- `Plugin`: The plugin that should be used for this policy.
- `PluginConfig`: The configuration for the plugin, this is a key value map that
  is passed to the plugin.

An example of this could look as follows:

```yaml
---
Type: DownSegmentRegistration
BestSetSize: 6
CandidateSetSize: 20
MaxExpTime: 42
RegistrationPolicies:
  - Name: Hidden
    Description: Hide segments that end on interface 1 and only make them available to ASes 1-ff00:0:110 and 1-ff00:0:113
    Matcher:
      Sequence: "0* 0#1"
    Plugin: HiddenSegmentRegistration
    PluginConfig:
      AccessList:
        - 1-ff00:0:110
        - 1-ff00:0:113
  - Name: Custom
    Description: Custom registration logic for segments that end on interface 2
    Matcher:
      Sequence: "0* 0#2"
    Plugin: CustomSegmentRegistration
    PluginConfig:
      Registry: 1-ff00:0:112
```
